website: http://ob-mc.net
name: OBMetaProducerBukkit
version: 1.0
api-version: 1.15
author: Fahrenheit451
main: net.obmc.OBMetaProducerBukkit.OBMetaProducer
description: Gather data from a server for use externally - maps, monitoring etc
